-- Generated mechanically from nextpnr/ecp5/dcu_bitstream.h.
{-# LANGUAGE OverloadedStrings #-}

module Lambdapnr.Arch.Ecp5.DcuBitstream (dcuWords) where

import Data.Map.Strict (Map)
import qualified Data.Map.Strict as M
import qualified Data.Text as T

import Lambdapnr.Kernel.IdString (IdString)
import Lambdapnr.Kernel.Netlist
import Lambdapnr.Kernel.Property (Property (..), propIsString, propAsString, propAsInt64)

-- | The DCU config words and their bit widths, in order.
dcuWords :: [(T.Text, Int)]
dcuWords = [
    ("DCU.DCU.CH0_AUTO_CALIB_EN", 1), -- id_CH0_AUTO_CALIB_EN default 0
    ("DCU.DCU.CH0_AUTO_FACQ_EN", 1), -- id_CH0_AUTO_FACQ_EN default 0
    ("DCU.DCU.CH0_BAND_THRESHOLD", 6), -- id_CH0_BAND_THRESHOLD default 0
    ("DCU.DCU.CH0_CALIB_CK_MODE", 1), -- id_CH0_CALIB_CK_MODE default 0
    ("DCU.DCU.CH0_CC_MATCH_1", 10), -- id_CH0_CC_MATCH_1 default 0
    ("DCU.DCU.CH0_CC_MATCH_2", 10), -- id_CH0_CC_MATCH_2 default 0
    ("DCU.DCU.CH0_CC_MATCH_3", 10), -- id_CH0_CC_MATCH_3 default 0
    ("DCU.DCU.CH0_CC_MATCH_4", 10), -- id_CH0_CC_MATCH_4 default 0
    ("DCU.DCU.CH0_CDR_CNT4SEL", 2), -- id_CH0_CDR_CNT4SEL default 0
    ("DCU.DCU.CH0_CDR_CNT8SEL", 2), -- id_CH0_CDR_CNT8SEL default 0
    ("DCU.DCU.CH0_CTC_BYPASS", 1), -- id_CH0_CTC_BYPASS default 0
    ("DCU.DCU.CH0_DCOATDCFG", 2), -- id_CH0_DCOATDCFG default 0
    ("DCU.DCU.CH0_DCOATDDLY", 2), -- id_CH0_DCOATDDLY default 0
    ("DCU.DCU.CH0_DCOBYPSATD", 1), -- id_CH0_DCOBYPSATD default 0
    ("DCU.DCU.CH0_DCOCALDIV", 3), -- id_CH0_DCOCALDIV default 0
    ("DCU.DCU.CH0_DCOCTLGI", 3), -- id_CH0_DCOCTLGI default 0
    ("DCU.DCU.CH0_DCODISBDAVOID", 1), -- id_CH0_DCODISBDAVOID default 0
    ("DCU.DCU.CH0_DCOFLTDAC", 2), -- id_CH0_DCOFLTDAC default 0
    ("DCU.DCU.CH0_DCOFTNRG", 3), -- id_CH0_DCOFTNRG default 0
    ("DCU.DCU.CH0_DCOIOSTUNE", 3), -- id_CH0_DCOIOSTUNE default 0
    ("DCU.DCU.CH0_DCOITUNE", 2), -- id_CH0_DCOITUNE default 0
    ("DCU.DCU.CH0_DCOITUNE4LSB", 3), -- id_CH0_DCOITUNE4LSB default 0
    ("DCU.DCU.CH0_DCOIUPDNX2", 1), -- id_CH0_DCOIUPDNX2 default 0
    ("DCU.DCU.CH0_DCONUOFLSB", 3), -- id_CH0_DCONUOFLSB default 0
    ("DCU.DCU.CH0_DCOSCALEI", 2), -- id_CH0_DCOSCALEI default 0
    ("DCU.DCU.CH0_DCOSTARTVAL", 3), -- id_CH0_DCOSTARTVAL default 0
    ("DCU.DCU.CH0_DCOSTEP", 2), -- id_CH0_DCOSTEP default 0
    ("DCU.DCU.CH0_DEC_BYPASS", 1), -- id_CH0_DEC_BYPASS default 0
    ("DCU.DCU.CH0_ENABLE_CG_ALIGN", 1), -- id_CH0_ENABLE_CG_ALIGN default 0
    ("DCU.DCU.CH0_ENC_BYPASS", 1), -- id_CH0_ENC_BYPASS default 0
    ("DCU.DCU.CH0_FF_RX_F_CLK_DIS", 1), -- id_CH0_FF_RX_F_CLK_DIS default 0
    ("DCU.DCU.CH0_FF_RX_H_CLK_EN", 1), -- id_CH0_FF_RX_H_CLK_EN default 0
    ("DCU.DCU.CH0_FF_TX_F_CLK_DIS", 1), -- id_CH0_FF_TX_F_CLK_DIS default 0
    ("DCU.DCU.CH0_FF_TX_H_CLK_EN", 1), -- id_CH0_FF_TX_H_CLK_EN default 0
    ("DCU.DCU.CH0_GE_AN_ENABLE", 1), -- id_CH0_GE_AN_ENABLE default 0
    ("DCU.DCU.CH0_INVERT_RX", 1), -- id_CH0_INVERT_RX default 0
    ("DCU.DCU.CH0_INVERT_TX", 1), -- id_CH0_INVERT_TX default 0
    ("DCU.DCU.CH0_LDR_CORE2TX_SEL", 1), -- id_CH0_LDR_CORE2TX_SEL default 0
    ("DCU.DCU.CH0_LDR_RX2CORE_SEL", 1), -- id_CH0_LDR_RX2CORE_SEL default 0
    ("DCU.DCU.CH0_LEQ_OFFSET_SEL", 1), -- id_CH0_LEQ_OFFSET_SEL default 0
    ("DCU.DCU.CH0_LEQ_OFFSET_TRIM", 3), -- id_CH0_LEQ_OFFSET_TRIM default 0
    ("DCU.DCU.CH0_LSM_DISABLE", 1), -- id_CH0_LSM_DISABLE default 0
    ("DCU.DCU.CH0_MATCH_2_ENABLE", 1), -- id_CH0_MATCH_2_ENABLE default 0
    ("DCU.DCU.CH0_MATCH_4_ENABLE", 1), -- id_CH0_MATCH_4_ENABLE default 0
    ("DCU.DCU.CH0_MIN_IPG_CNT", 2), -- id_CH0_MIN_IPG_CNT default 0
    ("DCU.DCU.CH0_PCIE_EI_EN", 1), -- id_CH0_PCIE_EI_EN default 0
    ("DCU.DCU.CH0_PCIE_MODE", 1), -- id_CH0_PCIE_MODE default 0
    ("DCU.DCU.CH0_PCS_DET_TIME_SEL", 2), -- id_CH0_PCS_DET_TIME_SEL default 0
    ("DCU.DCU.CH0_PDEN_SEL", 1), -- id_CH0_PDEN_SEL default 0
    ("DCU.DCU.CH0_PRBS_ENABLE", 1), -- id_CH0_PRBS_ENABLE default 0
    ("DCU.DCU.CH0_PRBS_LOCK", 1), -- id_CH0_PRBS_LOCK default 0
    ("DCU.DCU.CH0_PRBS_SELECTION", 1), -- id_CH0_PRBS_SELECTION default 0
    ("DCU.DCU.CH0_RATE_MODE_RX", 1), -- id_CH0_RATE_MODE_RX default 0
    ("DCU.DCU.CH0_RATE_MODE_TX", 1), -- id_CH0_RATE_MODE_TX default 0
    ("DCU.DCU.CH0_RCV_DCC_EN", 1), -- id_CH0_RCV_DCC_EN default 0
    ("DCU.DCU.CH0_REG_BAND_OFFSET", 4), -- id_CH0_REG_BAND_OFFSET default 0
    ("DCU.DCU.CH0_REG_BAND_SEL", 6), -- id_CH0_REG_BAND_SEL default 0
    ("DCU.DCU.CH0_REG_IDAC_EN", 1), -- id_CH0_REG_IDAC_EN default 0
    ("DCU.DCU.CH0_REG_IDAC_SEL", 10), -- id_CH0_REG_IDAC_SEL default 0
    ("DCU.DCU.CH0_REQ_EN", 1), -- id_CH0_REQ_EN default 0
    ("DCU.DCU.CH0_REQ_LVL_SET", 2), -- id_CH0_REQ_LVL_SET default 0
    ("DCU.DCU.CH0_RIO_MODE", 1), -- id_CH0_RIO_MODE default 0
    ("DCU.DCU.CH0_RLOS_SEL", 1), -- id_CH0_RLOS_SEL default 0
    ("DCU.DCU.CH0_RPWDNB", 1), -- id_CH0_RPWDNB default 0
    ("DCU.DCU.CH0_RTERM_RX", 5), -- id_CH0_RTERM_RX default 0
    ("DCU.DCU.CH0_RTERM_TX", 5), -- id_CH0_RTERM_TX default 0
    ("DCU.DCU.CH0_RXIN_CM", 2), -- id_CH0_RXIN_CM default 0
    ("DCU.DCU.CH0_RXTERM_CM", 2), -- id_CH0_RXTERM_CM default 0
    ("DCU.DCU.CH0_RX_DCO_CK_DIV", 3), -- id_CH0_RX_DCO_CK_DIV default 0
    ("DCU.DCU.CH0_RX_DIV11_SEL", 1), -- id_CH0_RX_DIV11_SEL default 0
    ("DCU.DCU.CH0_RX_GEAR_BYPASS", 1), -- id_CH0_RX_GEAR_BYPASS default 0
    ("DCU.DCU.CH0_RX_GEAR_MODE", 1), -- id_CH0_RX_GEAR_MODE default 0
    ("DCU.DCU.CH0_RX_LOS_CEQ", 2), -- id_CH0_RX_LOS_CEQ default 0
    ("DCU.DCU.CH0_RX_LOS_EN", 1), -- id_CH0_RX_LOS_EN default 0
    ("DCU.DCU.CH0_RX_LOS_HYST_EN", 1), -- id_CH0_RX_LOS_HYST_EN default 0
    ("DCU.DCU.CH0_RX_LOS_LVL", 3), -- id_CH0_RX_LOS_LVL default 0
    ("DCU.DCU.CH0_RX_RATE_SEL", 4), -- id_CH0_RX_RATE_SEL default 0
    ("DCU.DCU.CH0_RX_SB_BYPASS", 1), -- id_CH0_RX_SB_BYPASS default 0
    ("DCU.DCU.CH0_SB_BYPASS", 1), -- id_CH0_SB_BYPASS default 0
    ("DCU.DCU.CH0_SEL_SD_RX_CLK", 1), -- id_CH0_SEL_SD_RX_CLK default 0
    ("DCU.DCU.CH0_TDRV_DAT_SEL", 2), -- id_CH0_TDRV_DAT_SEL default 0
    ("DCU.DCU.CH0_TDRV_POST_EN", 1), -- id_CH0_TDRV_POST_EN default 0
    ("DCU.DCU.CH0_TDRV_PRE_EN", 1), -- id_CH0_TDRV_PRE_EN default 0
    ("DCU.DCU.CH0_TDRV_SLICE0_CUR", 3), -- id_CH0_TDRV_SLICE0_CUR default 0
    ("DCU.DCU.CH0_TDRV_SLICE0_SEL", 2), -- id_CH0_TDRV_SLICE0_SEL default 0
    ("DCU.DCU.CH0_TDRV_SLICE1_CUR", 3), -- id_CH0_TDRV_SLICE1_CUR default 0
    ("DCU.DCU.CH0_TDRV_SLICE1_SEL", 2), -- id_CH0_TDRV_SLICE1_SEL default 0
    ("DCU.DCU.CH0_TDRV_SLICE2_CUR", 2), -- id_CH0_TDRV_SLICE2_CUR default 0
    ("DCU.DCU.CH0_TDRV_SLICE2_SEL", 2), -- id_CH0_TDRV_SLICE2_SEL default 0
    ("DCU.DCU.CH0_TDRV_SLICE3_CUR", 2), -- id_CH0_TDRV_SLICE3_CUR default 0
    ("DCU.DCU.CH0_TDRV_SLICE3_SEL", 2), -- id_CH0_TDRV_SLICE3_SEL default 0
    ("DCU.DCU.CH0_TDRV_SLICE4_CUR", 2), -- id_CH0_TDRV_SLICE4_CUR default 0
    ("DCU.DCU.CH0_TDRV_SLICE4_SEL", 2), -- id_CH0_TDRV_SLICE4_SEL default 0
    ("DCU.DCU.CH0_TDRV_SLICE5_CUR", 2), -- id_CH0_TDRV_SLICE5_CUR default 0
    ("DCU.DCU.CH0_TDRV_SLICE5_SEL", 2), -- id_CH0_TDRV_SLICE5_SEL default 0
    ("DCU.DCU.CH0_TPWDNB", 1), -- id_CH0_TPWDNB default 0
    ("DCU.DCU.CH0_TX_CM_SEL", 2), -- id_CH0_TX_CM_SEL default 0
    ("DCU.DCU.CH0_TX_DIV11_SEL", 1), -- id_CH0_TX_DIV11_SEL default 0
    ("DCU.DCU.CH0_TX_GEAR_BYPASS", 1), -- id_CH0_TX_GEAR_BYPASS default 0
    ("DCU.DCU.CH0_TX_GEAR_MODE", 1), -- id_CH0_TX_GEAR_MODE default 0
    ("DCU.DCU.CH0_TX_POST_SIGN", 1), -- id_CH0_TX_POST_SIGN default 0
    ("DCU.DCU.CH0_TX_PRE_SIGN", 1), -- id_CH0_TX_PRE_SIGN default 0
    ("DCU.DCU.CH0_UC_MODE", 1), -- id_CH0_UC_MODE default 0
    ("DCU.DCU.CH0_UDF_COMMA_A", 10), -- id_CH0_UDF_COMMA_A default 0
    ("DCU.DCU.CH0_UDF_COMMA_B", 10), -- id_CH0_UDF_COMMA_B default 0
    ("DCU.DCU.CH0_UDF_COMMA_MASK", 10), -- id_CH0_UDF_COMMA_MASK default 0
    ("DCU.DCU.CH0_WA_BYPASS", 1), -- id_CH0_WA_BYPASS default 0
    ("DCU.DCU.CH0_WA_MODE", 1), -- id_CH0_WA_MODE default 0
    ("DCU.DCU.CH1_AUTO_CALIB_EN", 1), -- id_CH1_AUTO_CALIB_EN default 0
    ("DCU.DCU.CH1_AUTO_FACQ_EN", 1), -- id_CH1_AUTO_FACQ_EN default 0
    ("DCU.DCU.CH1_BAND_THRESHOLD", 6), -- id_CH1_BAND_THRESHOLD default 0
    ("DCU.DCU.CH1_CALIB_CK_MODE", 1), -- id_CH1_CALIB_CK_MODE default 0
    ("DCU.DCU.CH1_CC_MATCH_1", 10), -- id_CH1_CC_MATCH_1 default 0
    ("DCU.DCU.CH1_CC_MATCH_2", 10), -- id_CH1_CC_MATCH_2 default 0
    ("DCU.DCU.CH1_CC_MATCH_3", 10), -- id_CH1_CC_MATCH_3 default 0
    ("DCU.DCU.CH1_CC_MATCH_4", 10), -- id_CH1_CC_MATCH_4 default 0
    ("DCU.DCU.CH1_CDR_CNT4SEL", 2), -- id_CH1_CDR_CNT4SEL default 0
    ("DCU.DCU.CH1_CDR_CNT8SEL", 2), -- id_CH1_CDR_CNT8SEL default 0
    ("DCU.DCU.CH1_CTC_BYPASS", 1), -- id_CH1_CTC_BYPASS default 0
    ("DCU.DCU.CH1_DCOATDCFG", 2), -- id_CH1_DCOATDCFG default 0
    ("DCU.DCU.CH1_DCOATDDLY", 2), -- id_CH1_DCOATDDLY default 0
    ("DCU.DCU.CH1_DCOBYPSATD", 1), -- id_CH1_DCOBYPSATD default 0
    ("DCU.DCU.CH1_DCOCALDIV", 3), -- id_CH1_DCOCALDIV default 0
    ("DCU.DCU.CH1_DCOCTLGI", 3), -- id_CH1_DCOCTLGI default 0
    ("DCU.DCU.CH1_DCODISBDAVOID", 1), -- id_CH1_DCODISBDAVOID default 0
    ("DCU.DCU.CH1_DCOFLTDAC", 2), -- id_CH1_DCOFLTDAC default 0
    ("DCU.DCU.CH1_DCOFTNRG", 3), -- id_CH1_DCOFTNRG default 0
    ("DCU.DCU.CH1_DCOIOSTUNE", 3), -- id_CH1_DCOIOSTUNE default 0
    ("DCU.DCU.CH1_DCOITUNE", 2), -- id_CH1_DCOITUNE default 0
    ("DCU.DCU.CH1_DCOITUNE4LSB", 3), -- id_CH1_DCOITUNE4LSB default 0
    ("DCU.DCU.CH1_DCOIUPDNX2", 1), -- id_CH1_DCOIUPDNX2 default 0
    ("DCU.DCU.CH1_DCONUOFLSB", 3), -- id_CH1_DCONUOFLSB default 0
    ("DCU.DCU.CH1_DCOSCALEI", 2), -- id_CH1_DCOSCALEI default 0
    ("DCU.DCU.CH1_DCOSTARTVAL", 3), -- id_CH1_DCOSTARTVAL default 0
    ("DCU.DCU.CH1_DCOSTEP", 2), -- id_CH1_DCOSTEP default 0
    ("DCU.DCU.CH1_DEC_BYPASS", 1), -- id_CH1_DEC_BYPASS default 0
    ("DCU.DCU.CH1_ENABLE_CG_ALIGN", 1), -- id_CH1_ENABLE_CG_ALIGN default 0
    ("DCU.DCU.CH1_ENC_BYPASS", 1), -- id_CH1_ENC_BYPASS default 0
    ("DCU.DCU.CH1_FF_RX_F_CLK_DIS", 1), -- id_CH1_FF_RX_F_CLK_DIS default 0
    ("DCU.DCU.CH1_FF_RX_H_CLK_EN", 1), -- id_CH1_FF_RX_H_CLK_EN default 0
    ("DCU.DCU.CH1_FF_TX_F_CLK_DIS", 1), -- id_CH1_FF_TX_F_CLK_DIS default 0
    ("DCU.DCU.CH1_FF_TX_H_CLK_EN", 1), -- id_CH1_FF_TX_H_CLK_EN default 0
    ("DCU.DCU.CH1_GE_AN_ENABLE", 1), -- id_CH1_GE_AN_ENABLE default 0
    ("DCU.DCU.CH1_INVERT_RX", 1), -- id_CH1_INVERT_RX default 0
    ("DCU.DCU.CH1_INVERT_TX", 1), -- id_CH1_INVERT_TX default 0
    ("DCU.DCU.CH1_LDR_CORE2TX_SEL", 1), -- id_CH1_LDR_CORE2TX_SEL default 0
    ("DCU.DCU.CH1_LDR_RX2CORE_SEL", 1), -- id_CH1_LDR_RX2CORE_SEL default 0
    ("DCU.DCU.CH1_LEQ_OFFSET_SEL", 1), -- id_CH1_LEQ_OFFSET_SEL default 0
    ("DCU.DCU.CH1_LEQ_OFFSET_TRIM", 3), -- id_CH1_LEQ_OFFSET_TRIM default 0
    ("DCU.DCU.CH1_LSM_DISABLE", 1), -- id_CH1_LSM_DISABLE default 0
    ("DCU.DCU.CH1_MATCH_2_ENABLE", 1), -- id_CH1_MATCH_2_ENABLE default 0
    ("DCU.DCU.CH1_MATCH_4_ENABLE", 1), -- id_CH1_MATCH_4_ENABLE default 0
    ("DCU.DCU.CH1_MIN_IPG_CNT", 2), -- id_CH1_MIN_IPG_CNT default 0
    ("DCU.DCU.CH1_PCIE_EI_EN", 1), -- id_CH1_PCIE_EI_EN default 0
    ("DCU.DCU.CH1_PCIE_MODE", 1), -- id_CH1_PCIE_MODE default 0
    ("DCU.DCU.CH1_PCS_DET_TIME_SEL", 2), -- id_CH1_PCS_DET_TIME_SEL default 0
    ("DCU.DCU.CH1_PDEN_SEL", 1), -- id_CH1_PDEN_SEL default 0
    ("DCU.DCU.CH1_PRBS_ENABLE", 1), -- id_CH1_PRBS_ENABLE default 0
    ("DCU.DCU.CH1_PRBS_LOCK", 1), -- id_CH1_PRBS_LOCK default 0
    ("DCU.DCU.CH1_PRBS_SELECTION", 1), -- id_CH1_PRBS_SELECTION default 0
    ("DCU.DCU.CH1_RATE_MODE_RX", 1), -- id_CH1_RATE_MODE_RX default 0
    ("DCU.DCU.CH1_RATE_MODE_TX", 1), -- id_CH1_RATE_MODE_TX default 0
    ("DCU.DCU.CH1_RCV_DCC_EN", 1), -- id_CH1_RCV_DCC_EN default 0
    ("DCU.DCU.CH1_REG_BAND_OFFSET", 4), -- id_CH1_REG_BAND_OFFSET default 0
    ("DCU.DCU.CH1_REG_BAND_SEL", 6), -- id_CH1_REG_BAND_SEL default 0
    ("DCU.DCU.CH1_REG_IDAC_EN", 1), -- id_CH1_REG_IDAC_EN default 0
    ("DCU.DCU.CH1_REG_IDAC_SEL", 10), -- id_CH1_REG_IDAC_SEL default 0
    ("DCU.DCU.CH1_REQ_EN", 1), -- id_CH1_REQ_EN default 0
    ("DCU.DCU.CH1_REQ_LVL_SET", 2), -- id_CH1_REQ_LVL_SET default 0
    ("DCU.DCU.CH1_RIO_MODE", 1), -- id_CH1_RIO_MODE default 0
    ("DCU.DCU.CH1_RLOS_SEL", 1), -- id_CH1_RLOS_SEL default 0
    ("DCU.DCU.CH1_RPWDNB", 1), -- id_CH1_RPWDNB default 0
    ("DCU.DCU.CH1_RTERM_RX", 5), -- id_CH1_RTERM_RX default 0
    ("DCU.DCU.CH1_RTERM_TX", 5), -- id_CH1_RTERM_TX default 0
    ("DCU.DCU.CH1_RXIN_CM", 2), -- id_CH1_RXIN_CM default 0
    ("DCU.DCU.CH1_RXTERM_CM", 2), -- id_CH1_RXTERM_CM default 0
    ("DCU.DCU.CH1_RX_DCO_CK_DIV", 3), -- id_CH1_RX_DCO_CK_DIV default 0
    ("DCU.DCU.CH1_RX_DIV11_SEL", 1), -- id_CH1_RX_DIV11_SEL default 0
    ("DCU.DCU.CH1_RX_GEAR_BYPASS", 1), -- id_CH1_RX_GEAR_BYPASS default 0
    ("DCU.DCU.CH1_RX_GEAR_MODE", 1), -- id_CH1_RX_GEAR_MODE default 0
    ("DCU.DCU.CH1_RX_LOS_CEQ", 2), -- id_CH1_RX_LOS_CEQ default 0
    ("DCU.DCU.CH1_RX_LOS_EN", 1), -- id_CH1_RX_LOS_EN default 0
    ("DCU.DCU.CH1_RX_LOS_HYST_EN", 1), -- id_CH1_RX_LOS_HYST_EN default 0
    ("DCU.DCU.CH1_RX_LOS_LVL", 3), -- id_CH1_RX_LOS_LVL default 0
    ("DCU.DCU.CH1_RX_RATE_SEL", 4), -- id_CH1_RX_RATE_SEL default 0
    ("DCU.DCU.CH1_RX_SB_BYPASS", 1), -- id_CH1_RX_SB_BYPASS default 0
    ("DCU.DCU.CH1_SB_BYPASS", 1), -- id_CH1_SB_BYPASS default 0
    ("DCU.DCU.CH1_SEL_SD_RX_CLK", 1), -- id_CH1_SEL_SD_RX_CLK default 0
    ("DCU.DCU.CH1_TDRV_DAT_SEL", 2), -- id_CH1_TDRV_DAT_SEL default 0
    ("DCU.DCU.CH1_TDRV_POST_EN", 1), -- id_CH1_TDRV_POST_EN default 0
    ("DCU.DCU.CH1_TDRV_PRE_EN", 1), -- id_CH1_TDRV_PRE_EN default 0
    ("DCU.DCU.CH1_TDRV_SLICE0_CUR", 3), -- id_CH1_TDRV_SLICE0_CUR default 0
    ("DCU.DCU.CH1_TDRV_SLICE0_SEL", 2), -- id_CH1_TDRV_SLICE0_SEL default 0
    ("DCU.DCU.CH1_TDRV_SLICE1_CUR", 3), -- id_CH1_TDRV_SLICE1_CUR default 0
    ("DCU.DCU.CH1_TDRV_SLICE1_SEL", 2), -- id_CH1_TDRV_SLICE1_SEL default 0
    ("DCU.DCU.CH1_TDRV_SLICE2_CUR", 2), -- id_CH1_TDRV_SLICE2_CUR default 0
    ("DCU.DCU.CH1_TDRV_SLICE2_SEL", 2), -- id_CH1_TDRV_SLICE2_SEL default 0
    ("DCU.DCU.CH1_TDRV_SLICE3_CUR", 2), -- id_CH1_TDRV_SLICE3_CUR default 0
    ("DCU.DCU.CH1_TDRV_SLICE3_SEL", 2), -- id_CH1_TDRV_SLICE3_SEL default 0
    ("DCU.DCU.CH1_TDRV_SLICE4_CUR", 2), -- id_CH1_TDRV_SLICE4_CUR default 0
    ("DCU.DCU.CH1_TDRV_SLICE4_SEL", 2), -- id_CH1_TDRV_SLICE4_SEL default 0
    ("DCU.DCU.CH1_TDRV_SLICE5_CUR", 2), -- id_CH1_TDRV_SLICE5_CUR default 0
    ("DCU.DCU.CH1_TDRV_SLICE5_SEL", 2), -- id_CH1_TDRV_SLICE5_SEL default 0
    ("DCU.DCU.CH1_TPWDNB", 1), -- id_CH1_TPWDNB default 0
    ("DCU.DCU.CH1_TX_CM_SEL", 2), -- id_CH1_TX_CM_SEL default 0
    ("DCU.DCU.CH1_TX_DIV11_SEL", 1), -- id_CH1_TX_DIV11_SEL default 0
    ("DCU.DCU.CH1_TX_GEAR_BYPASS", 1), -- id_CH1_TX_GEAR_BYPASS default 0
    ("DCU.DCU.CH1_TX_GEAR_MODE", 1), -- id_CH1_TX_GEAR_MODE default 0
    ("DCU.DCU.CH1_TX_POST_SIGN", 1), -- id_CH1_TX_POST_SIGN default 0
    ("DCU.DCU.CH1_TX_PRE_SIGN", 1), -- id_CH1_TX_PRE_SIGN default 0
    ("DCU.DCU.CH1_UC_MODE", 1), -- id_CH1_UC_MODE default 0
    ("DCU.DCU.CH1_UDF_COMMA_A", 10), -- id_CH1_UDF_COMMA_A default 0
    ("DCU.DCU.CH1_UDF_COMMA_B", 10), -- id_CH1_UDF_COMMA_B default 0
    ("DCU.DCU.CH1_UDF_COMMA_MASK", 10), -- id_CH1_UDF_COMMA_MASK default 0
    ("DCU.DCU.CH1_WA_BYPASS", 1), -- id_CH1_WA_BYPASS default 0
    ("DCU.DCU.CH1_WA_MODE", 1), -- id_CH1_WA_MODE default 0
    ("DCU.DCU.D_BITCLK_FROM_ND_EN", 1), -- id_D_BITCLK_FROM_ND_EN default 0
    ("DCU.DCU.D_BITCLK_LOCAL_EN", 1), -- id_D_BITCLK_LOCAL_EN default 0
    ("DCU.DCU.D_BITCLK_ND_EN", 1), -- id_D_BITCLK_ND_EN default 0
    ("DCU.DCU.D_BUS8BIT_SEL", 1), -- id_D_BUS8BIT_SEL default 0
    ("DCU.DCU.D_CDR_LOL_SET", 2), -- id_D_CDR_LOL_SET default 0
    ("DCU.DCU.D_CMUSETBIASI", 2), -- id_D_CMUSETBIASI default 0
    ("DCU.DCU.D_CMUSETI4CPP", 4), -- id_D_CMUSETI4CPP default 0
    ("DCU.DCU.D_CMUSETI4CPZ", 4), -- id_D_CMUSETI4CPZ default 0
    ("DCU.DCU.D_CMUSETI4VCO", 2), -- id_D_CMUSETI4VCO default 0
    ("DCU.DCU.D_CMUSETICP4P", 2), -- id_D_CMUSETICP4P default 0
    ("DCU.DCU.D_CMUSETICP4Z", 3), -- id_D_CMUSETICP4Z default 0
    ("DCU.DCU.D_CMUSETINITVCT", 2), -- id_D_CMUSETINITVCT default 0
    ("DCU.DCU.D_CMUSETISCL4VCO", 3), -- id_D_CMUSETISCL4VCO default 0
    ("DCU.DCU.D_CMUSETP1GM", 3), -- id_D_CMUSETP1GM default 0
    ("DCU.DCU.D_CMUSETP2AGM", 3), -- id_D_CMUSETP2AGM default 0
    ("DCU.DCU.D_CMUSETZGM", 3), -- id_D_CMUSETZGM default 0
    ("DCU.DCU.D_DCO_CALIB_TIME_SEL", 2), -- id_D_DCO_CALIB_TIME_SEL default 0
    ("DCU.DCU.D_HIGH_MARK", 4), -- id_D_HIGH_MARK default 0
    ("DCU.DCU.D_IB_PWDNB", 1), -- id_D_IB_PWDNB default 0
    ("DCU.DCU.D_ISETLOS", 8), -- id_D_ISETLOS default 0
    ("DCU.DCU.D_LOW_MARK", 4), -- id_D_LOW_MARK default 0
    ("DCU.DCU.D_MACROPDB", 1), -- id_D_MACROPDB default 0
    ("DCU.DCU.D_PD_ISET", 2), -- id_D_PD_ISET default 0
    ("DCU.DCU.D_PLL_LOL_SET", 2), -- id_D_PLL_LOL_SET default 0
    ("DCU.DCU.D_REFCK_MODE", 3), -- id_D_REFCK_MODE default 0
    ("DCU.DCU.D_REQ_ISET", 3), -- id_D_REQ_ISET default 0
    ("DCU.DCU.D_RG_EN", 1), -- id_D_RG_EN default 0
    ("DCU.DCU.D_RG_SET", 2), -- id_D_RG_SET default 0
    ("DCU.DCU.D_SETICONST_AUX", 2), -- id_D_SETICONST_AUX default 0
    ("DCU.DCU.D_SETICONST_CH", 2), -- id_D_SETICONST_CH default 0
    ("DCU.DCU.D_SETIRPOLY_AUX", 2), -- id_D_SETIRPOLY_AUX default 0
    ("DCU.DCU.D_SETIRPOLY_CH", 2), -- id_D_SETIRPOLY_CH default 0
    ("DCU.DCU.D_SETPLLRC", 6), -- id_D_SETPLLRC default 0
    ("DCU.DCU.D_SYNC_LOCAL_EN", 1), -- id_D_SYNC_LOCAL_EN default 0
    ("DCU.DCU.D_SYNC_ND_EN", 1), -- id_D_SYNC_ND_EN default 0
    ("DCU.DCU.D_TXPLL_PWDNB", 1), -- id_D_TXPLL_PWDNB default 0
    ("DCU.DCU.D_TX_VCO_CK_DIV", 3), -- id_D_TX_VCO_CK_DIV default 0
    ("DCU.DCU.D_XGE_MODE", 1) -- id_D_XGE_MODE default 0
    ]
